// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJkq02kuKELSwm3NudoHPWTCjFcrVRFu8',
    appId: '1:449980123915:web:10f82cfc84a58b7dfdf00e',
    messagingSenderId: '449980123915',
    projectId: 'flutter-bloc-crud',
    authDomain: 'flutter-bloc-crud.firebaseapp.com',
    storageBucket: 'flutter-bloc-crud.appspot.com',
    measurementId: 'G-BC4YNV1036',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3YBI3TAkds-qvsBQ9sNqKm-LxU5UA6GA',
    appId: '1:449980123915:android:94b40e1f0b9f7e1dfdf00e',
    messagingSenderId: '449980123915',
    projectId: 'flutter-bloc-crud',
    storageBucket: 'flutter-bloc-crud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApv9vX3DoRwXkSVBovcsfhv7OKiWuFSzk',
    appId: '1:449980123915:ios:1eb1cbc84009aff0fdf00e',
    messagingSenderId: '449980123915',
    projectId: 'flutter-bloc-crud',
    storageBucket: 'flutter-bloc-crud.appspot.com',
    iosClientId: '449980123915-kihh219fuv4gc5klf10den7rm6ur8ivs.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.presents.flutterbloccrud',
  );
}
